apiVersion: v1
kind: Pod
metadata:
  name: pod-microservice2-k
  labels:
    app: microservice2k
spec:
    containers:
      - name: microservice2-k-container
        image: cristiank/microservice2-k:lastest
        ports:
        - containerPort: 4000
        
---
apiVersion: v1
kind: Service
metadata:
  name: microservice2-service
spec:
  selector:
    app: microservice2k
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4000
  type: ClusterIP
