apiVersion: v1
kind: Pod
metadata:
  name: pod-microservice-k
  labels:
    app: microservicek
spec:
    containers:
      - name: microservice-k-container
        image: cristiank/microservice-k:lastest
        ports:
        - containerPort: 4000
        
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-service
spec:
  selector:
    app: microservicek
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP
