apiVersion: v1
kind: Pod
metadata:
  name: pod-orchestrator
  labels:
    app: orchestrator
spec:
    containers:
      - name: orchestrator-container
        image: cristiank/orchestrator-k8:latest
        ports:
          - containerPort: 80

--- 
apiVersion: v1
kind: Service
metadata:
  name: orchestrator-service
spec:
  selector:
    app: orchestrator
  ports:
      - protocol: TCP
        port: 80
        targetPort: 80
        name: http-server
  type: NodePort